[package]
name = "dotlin_lexer"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
# dotlin_span.workspace = true
# dotlin_diagnostics.workspace = true

# logos.workspace = true
# unicode-xid = "0.2"

[dev-dependencies]
criterion = "0.5"
