[package]
name = "dotlin_runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
# Build as a cdylib on Windows so link.exe can see exported C symbols
crate-type = ["cdylib"]

[dependencies]
